# -*- coding: utf-8 -*-
"""Projeto Final - Classificação de animais

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEd9RcJRYTyAty3H3RVW24SBHeQbHLGR
"""

#features (1 sim, 0 não)
#pelo longo?
#perna curta?
# faz latido

gato1 = [0, 1, 0]
gato2 = [0, 1, 1]
gato3 = [1, 1, 0]

cachorro1 = [0, 1, 1]
cachorro2 = [1, 0, 1]
cachorro3 = [1, 1, 1]

# 1 => gato, 0 => cachorro
dados = [gato1, gato2, gato3, cachorro1, cachorro2, cachorro3]
classes = [1,1,1,0,0,0]

treino_x = [gato1, gato2, gato3, cachorro1, cachorro2, cachorro3]
treino_y = [1,1,1,0,0,0] #labels / etiquetas

from sklearn.svm  import LinearSVC
model = LinearSVC()
model.fit(dados,classes)

animal_misterioso = [1,1,1]
model.predict([animal_misterioso])

misterio1 = [1, 1, 1]
misterio2 = [1, 1, 0]
misterio3 = [0, 1, 1]
testes = [misterio1, misterio2, misterio3]
model.predict(testes)

testes_classes

previsoes == testes_classes

previsoes

teste_x = [misterio1, misterio2, misterio3]
teste_y = [0, 1, 1]
previsoes = model.predict(teste_x)

testes

previsoes

corretos= (previsoes == teste_y).sum()
total = len(teste_x)
taxa_de_acerto = corretos/total
print("Taxa de acerto: ", taxa_de_acerto * 100)